{
 "title": "[compact-block] Compact block reconstruction time",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } },
   { "name": "bandwidth_mode", "query": { "query": "label_values(bandwidth)" } },
   { "name": "tx_requested", "query": { "query": "label_values(tx_requested)" } }
  ]
 },
 "panels": [
  { "title": "Reconstruction time dispersion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconstruction time dispersion (tx requested=$tx_requested)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "tx_requested",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "peerobserver_log_compact_block_reconstruction_time{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}\r\n  and\r\nchanges(peerobserver_log_compact_block_reconstruction_count{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}[$__interval]) > 0",
     "legendFormat": "{{host}} {{bandwidth}}"
    },
    {
     "expr": "avg_over_time(\r\n  (\r\n    peerobserver_log_compact_block_reconstruction_time{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}\r\n      and\r\n    changes(peerobserver_log_compact_block_reconstruction_count{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}[1d]) > 0\r\n  )[1d:]\r\n)",
     "legendFormat": "{{host}} {{bandwidth}} avg 1d"
    },
    {
     "expr": "max(peerobserver_validation_block_connected_latest_height) by (host) > 0",
     "legendFormat": "{{host}} height"
    }
   ]
  },
  {
   "title": "Aggregated time elapsed (tx requested=$tx_requested)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "repeat": "tx_requested",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "peerobserver_log_compact_block_reconstruction_time{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}\r\n  and\r\nchanges(peerobserver_log_compact_block_reconstruction_count{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}[$__interval]) > 0",
     "legendFormat": "{{host}} {{bandwidth}}"
    }
   ]
  },
  {
   "title": "Reconstruction time heatmap (tx requested=$tx_requested)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "repeat": "tx_requested",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "last_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"$tx_requested\", bandwidth=~\"$bandwidth_mode\"}[$__interval])",
     "legendFormat": "{{host}} {{bandwidth}}"
    }
   ]
  },
  {
   "title": "Reconstruction time by day (bandwidth=$bandwidth_mode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "bandwidth_mode"
  },
  {
   "title": "Reconstruction time by day - $host (bandwidth=$bandwidth_mode, tx requested=false)",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"false\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile_over_time(0.75, peerobserver_log_compact_block_reconstruction_time{tx_requested=\"false\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.25, peerobserver_log_compact_block_reconstruction_time{tx_requested=\"false\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "max_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"false\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "min_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"false\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Reconstruction time by day - $host (bandwidth=$bandwidth_mode, tx requested=true)",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"true\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile_over_time(0.75, peerobserver_log_compact_block_reconstruction_time{tx_requested=\"true\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.25, peerobserver_log_compact_block_reconstruction_time{tx_requested=\"true\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "max_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"true\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "min_over_time(peerobserver_log_compact_block_reconstruction_time{tx_requested=\"true\", bandwidth=\"$bandwidth_mode\", host=\"$host\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  }
 ]
}